#!/bin/bash
set -e

CURRENT_BRANCH=`git branch | grep \* | cut -d ' ' -f2`
CURRENT_CODELAB=`echo $CURRENT_BRANCH | cut -d "-" -f1`
PREVIOUS_CODELAB=`echo "$CURRENT_CODELAB - 1" | bc`
NEXT_CODELAB=`echo "$CURRENT_CODELAB + 1" | bc`

function nextBranch() {
	if [[ $CURRENT_BRANCH == "common" ]]; then
		NEXT_BRANCH="101-starter"
	elif [[ $CURRENT_BRANCH == "104-complete" ]]; then
		NEXT_BRANCH="master"
	elif [[ $CURRENT_BRANCH == "111-complete" ]]; then
		NEXT_BRANCH=""
	elif [[ $CURRENT_BRANCH == *-starter ]]; then
		NEXT_BRANCH="$CURRENT_CODELAB-complete"
	elif [[ $CURRENT_BRANCH == *-complete ]]; then
		NEXT_BRANCH="$NEXT_CODELAB-starter"
	fi
}

function rebaseNext() {
# Calculate the next branch. If we just did 104-complete, switch over to 111.
	if [ "$CURRENT_BRANCH" == "master" ]; then
		NEXT_BRANCH="111-starter"
		CURRENT_BRANCH="common"
	else
		nextBranch
	fi

	if [ "$NEXT_BRANCH" != "" ]; then
		git checkout $NEXT_BRANCH
		git rebase -X ours -i $CURRENT_BRANCH
		git diff $NEXT_BRANCH origin/$NEXT_BRANCH
		echo "Moved $NEXT_BRANCH onto $CURRENT_BRANCH. Make sure everything looks good and then run this script again."
		echo "If you are just moving this commit (you didn't make any changes to $NEXT_BRANCH) and something looks wrong, you can try again by running: git reset $NEXT_BRANCH origin/$NEXT_BRANCH && git checkout $CURRENT_BRANCH"
	else
		echo "Done"
	fi
}

rebaseNext
